name: ğŸ„ Test CLI

on:
  workflow_dispatch: {}

  pull_request:
    branches:
      - "*"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - ".github/workflows/unit-tests.yml"
      - "src/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: â­ Power up repository
      uses: actions/checkout@v4
    
    - name: ğŸŒŸ Level up with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: ğŸª™ Collect dependencies
      run: yarn install --frozen-lockfile

    - name: ğŸ—ï¸ Build the castle
      run: yarn build
      
    - name: ğŸŒˆ Install envilder globally
      run: yarn global add file:.
      
    - name: ğŸ® Test cli envilder
      run: yarn validate-cli
